### PR TITLE
Move Driver modules into separate files

### PR DESCRIPTION
**Pull request by reneeb**

### CODE REVIEW

**Comment by mlawren** [comment]
Thanks for the pull request Renée! Unfortunately I didn't tell you 
about how I manage my branches, and so it is difficult for me to merge 
this request as it is. Here is how I do things:

```
devel: where development happens

devel-dist: automatically generated from the devel branch using a
script I run locally that basically calls "make manifest dist" and
then "git commit".  Hence the MANIFEST file is always automatically
populated.

master: only ever merge from devel when stable releases are made

master-dist: only ever merge from devel-dist when stable releases 
are made
```

I don't know how the results of the CPAN request challenge are 
recorded. I can either cherry-pick your 71819b6 commit onto devel, or
you could re-work the pull request against the devel branch, dropping
the second commit. Let me know which is best?

**Comment by mlawren** [comment]
Whoops - I got the master-dist branch name wrong. It is actually "dist" as you already know.

**Comment by mlawren** [comment]
I've merged the single commit onto the newly named 'dev' branch, and I'll close this pull request now. Thanks for the help - and if you need the favour returned somewhere let me know.

**Comment by reneeb** [comment]
Thanks. Sorry for the silence. I was too busy the last month.

**Comment by neilb** [comment]
:+1:

**Pull request closed without merging**
